name: CI
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWSCLOUDFORMATIONCONFIG: "{\"awscloudformation\":{\
  \"configLevel\":\"project\",\
  \"useProfile\":true,\
  \"profileName\":\"user\",\
  \"accessKeyId\":\"test\",\
  \"secretAccessKey\":\"test\"\
  }}"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Lint
        run: |
          npm -g install .
          npm run lint
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id "AKIAI44QH8DHBEXAMPLE" --profile user
          aws configure set aws_secret_access_key "je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY" --profile user 
          aws configure set region "us-east-1" --profile user
          aws configure set output "json" --profile user
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Localstack
        run: pip install localstack
      - name: Start and wait for localstack
        timeout-minutes: 5
        run: |
          docker pull localstack/localstack:latest
          localstack start -d
          localstack wait -t 30
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli
      - name: Set up Amplify Plugin
        run: amplify plugin scan
      - name: Init Amplify Project
        run: |
          mkdir test_project
          cd test_project
          amplify init --envName test --yes --providers ${{ env.AWSCLOUDFORMATIONCONFIG}} --use-localstack true
      - name: Deploy Amplify S3 Storage Resource
        working-directory: test_project
        run: |
          amplify add storage --type S3 --name myStorage --bucketName my-bucket --yes
          amplify push --use-localstack true
